/********************************************************************
* code/mcalimagingDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error code/mcalimagingDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablemcalimagingDict();
extern void G__cpp_setup_inheritancemcalimagingDict();
extern void G__cpp_setup_typetablemcalimagingDict();
extern void G__cpp_setup_memvarmcalimagingDict();
extern void G__cpp_setup_globalmcalimagingDict();
extern void G__cpp_setup_memfuncmcalimagingDict();
extern void G__cpp_setup_funcmcalimagingDict();
extern void G__set_cpp_environmentmcalimagingDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "mcalguess.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__mcalimagingDictLN_TClass;
extern G__linked_taginfo G__mcalimagingDictLN_TBuffer;
extern G__linked_taginfo G__mcalimagingDictLN_TMemberInspector;
extern G__linked_taginfo G__mcalimagingDictLN_TObject;
extern G__linked_taginfo G__mcalimagingDictLN_TNamed;
extern G__linked_taginfo G__mcalimagingDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__mcalimagingDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mcalimagingDictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR;
extern G__linked_taginfo G__mcalimagingDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__mcalimagingDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__mcalimagingDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__mcalimagingDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__mcalimagingDictLN_TH2F;
extern G__linked_taginfo G__mcalimagingDictLN_mcalguess;

/* STUB derived class for protected member access */
