//
// File generated by /scratch/prod/root/root_v5.34.24/bin/rootcint at Wed Jul 27 10:19:42 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME codedImcalimagingDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "mcalimagingDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void mcalguess_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_mcalguess(void *p = 0);
   static void *newArray_mcalguess(Long_t size, void *p);
   static void delete_mcalguess(void *p);
   static void deleteArray_mcalguess(void *p);
   static void destruct_mcalguess(void *p);
   static void streamer_mcalguess(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::mcalguess*)
   {
      ::mcalguess *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::mcalguess >(0);
      static ::ROOT::TGenericClassInfo 
         instance("mcalguess", ::mcalguess::Class_Version(), "code/mcalguess.h", 18,
                  typeid(::mcalguess), ::ROOT::DefineBehavior(ptr, ptr),
                  &::mcalguess::Dictionary, isa_proxy, 0,
                  sizeof(::mcalguess) );
      instance.SetNew(&new_mcalguess);
      instance.SetNewArray(&newArray_mcalguess);
      instance.SetDelete(&delete_mcalguess);
      instance.SetDeleteArray(&deleteArray_mcalguess);
      instance.SetDestructor(&destruct_mcalguess);
      instance.SetStreamerFunc(&streamer_mcalguess);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::mcalguess*)
   {
      return GenerateInitInstanceLocal((::mcalguess*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::mcalguess*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr mcalguess::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *mcalguess::Class_Name()
{
   return "mcalguess";
}

//______________________________________________________________________________
const char *mcalguess::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::mcalguess*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int mcalguess::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::mcalguess*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void mcalguess::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::mcalguess*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *mcalguess::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::mcalguess*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void mcalguess::Streamer(TBuffer &R__b)
{
   // Stream an object of class mcalguess.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TNamed::Streamer(R__b);
      R__b.ReadStaticArray((int*)nevt);
      R__b >> dim;
      R__b >> econv;
      R__b >> mguess;
      R__b >> kbin;
      R__b.ReadStaticArray((double*)energybins);
      R__b.ReadStaticArray((double*)avgenergy);
      R__b.ReadStaticArray((float*)evtprob);
      R__b.ReadStaticArray((float*)ebinX);
      R__b.ReadStaticArray((float*)ebinZ);
      R__b.ReadStaticArray((float*)prob);
      R__b >> currnbarsX;
      R__b >> currnbarsZ;
      R__b >> curreX;
      R__b >> curreZ;
      R__b >> avgE;
      R__b.CheckByteCount(R__s, R__c, mcalguess::IsA());
   } else {
      R__c = R__b.WriteVersion(mcalguess::IsA(), kTRUE);
      TNamed::Streamer(R__b);
      R__b.WriteArray(nevt, 6);
      R__b << dim;
      R__b << econv;
      R__b << mguess;
      R__b << kbin;
      R__b.WriteArray(energybins, 7);
      R__b.WriteArray(avgenergy, 6);
      R__b.WriteArray(evtprob, 6);
      R__b.WriteArray(ebinX, 25);
      R__b.WriteArray(ebinZ, 25);
      R__b.WriteArray((float*)prob, 884736);
      R__b << currnbarsX;
      R__b << currnbarsZ;
      R__b << curreX;
      R__b << curreZ;
      R__b << avgE;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void mcalguess::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class mcalguess.
      TClass *R__cl = ::mcalguess::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nevt[6]", nevt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dim", &dim);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "econv", &econv);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mguess", &mguess);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "kbin", &kbin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "energybins[7]", energybins);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "avgenergy[6]", avgenergy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "evtprob[6]", evtprob);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ebinX[25]", ebinX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ebinZ[25]", ebinZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "prob[6][16][16][24][24]", prob);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "currnbarsX", &currnbarsX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "currnbarsZ", &currnbarsZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "curreX", &curreX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "curreZ", &curreZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "avgE", &avgE);
      TNamed::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_mcalguess(void *p) {
      return  p ? new(p) ::mcalguess : new ::mcalguess;
   }
   static void *newArray_mcalguess(Long_t nElements, void *p) {
      return p ? new(p) ::mcalguess[nElements] : new ::mcalguess[nElements];
   }
   // Wrapper around operator delete
   static void delete_mcalguess(void *p) {
      delete ((::mcalguess*)p);
   }
   static void deleteArray_mcalguess(void *p) {
      delete [] ((::mcalguess*)p);
   }
   static void destruct_mcalguess(void *p) {
      typedef ::mcalguess current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_mcalguess(TBuffer &buf, void *obj) {
      ((::mcalguess*)obj)->::mcalguess::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::mcalguess

/********************************************************
* code/mcalimagingDict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablemcalimagingDict();

extern "C" void G__set_cpp_environmentmcalimagingDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("mcalguess.h");
  G__cpp_reset_tagtablemcalimagingDict();
}
#include <new>
extern "C" int G__cpp_dllrevmcalimagingDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* mcalguess */
static int G__mcalimagingDict_674_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   mcalguess* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new mcalguess[n];
     } else {
       p = new((void*) gvp) mcalguess[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new mcalguess;
     } else {
       p = new((void*) gvp) mcalguess;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mcalimagingDictLN_mcalguess));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mcalguess*) G__getstructoffset())->Fill((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (float) G__double(libp->para[3])
, (float) G__double(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 73, (long) ((mcalguess*) G__getstructoffset())->GetNEvents());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((mcalguess*) G__getstructoffset())->GetNEvents((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 70, (long) ((mcalguess*) G__getstructoffset())->GetBinProb());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      G__letint(result7, 70, (long) ((mcalguess*) G__getstructoffset())->GetBinProb((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (float) G__double(libp->para[2]), (float) G__double(libp->para[3])
, (bool) G__int(libp->para[4])));
      break;
   case 4:
      G__letint(result7, 70, (long) ((mcalguess*) G__getstructoffset())->GetBinProb((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (float) G__double(libp->para[2]), (float) G__double(libp->para[3])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((mcalguess*) G__getstructoffset())->GetBestBin());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      G__letint(result7, 105, (long) ((mcalguess*) G__getstructoffset())->GetBestBin((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (float) G__double(libp->para[2]), (float) G__double(libp->para[3])
, (bool) G__int(libp->para[4])));
      break;
   case 4:
      G__letint(result7, 105, (long) ((mcalguess*) G__getstructoffset())->GetBestBin((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (float) G__double(libp->para[2]), (float) G__double(libp->para[3])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((mcalguess*) G__getstructoffset())->GetBestEnergy());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      G__letint(result7, 105, (long) ((mcalguess*) G__getstructoffset())->GetBestEnergy((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (float) G__double(libp->para[2]), (float) G__double(libp->para[3])
, (bool) G__int(libp->para[4])));
      break;
   case 4:
      G__letint(result7, 105, (long) ((mcalguess*) G__getstructoffset())->GetBestEnergy((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (float) G__double(libp->para[2]), (float) G__double(libp->para[3])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 85, (long) ((mcalguess*) G__getstructoffset())->GetBarCorr((int) G__int(libp->para[0]), (bool) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 85, (long) ((mcalguess*) G__getstructoffset())->GetBarCorr((int) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 85, (long) ((mcalguess*) G__getstructoffset())->GetEnergyCorr((int) G__int(libp->para[0]), (bool) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 85, (long) ((mcalguess*) G__getstructoffset())->GetEnergyCorr((int) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 102, (double) ((mcalguess*) G__getstructoffset())->GetKalmanProb((float) G__double(libp->para[0]), (bool) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 102, (double) ((mcalguess*) G__getstructoffset())->GetKalmanProb((float) G__double(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 102, (double) ((mcalguess*) G__getstructoffset())->GetKalmanBin((float) G__double(libp->para[0]), (bool) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 102, (double) ((mcalguess*) G__getstructoffset())->GetKalmanBin((float) G__double(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mcalguess*) G__getstructoffset())->Normalize((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mcalguess*) G__getstructoffset())->SetEnergyArray((double*) G__int(libp->para[0]), (float*) G__int(libp->para[1])
, (float*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) mcalguess::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) mcalguess::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) mcalguess::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      mcalguess::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((mcalguess*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) mcalguess::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) mcalguess::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) mcalguess::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mcalimagingDict_674_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) mcalguess::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__mcalimagingDict_674_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   mcalguess* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new mcalguess(*(mcalguess*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mcalimagingDictLN_mcalguess));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef mcalguess G__Tmcalguess;
static int G__mcalimagingDict_674_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (mcalguess*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((mcalguess*) (soff+(sizeof(mcalguess)*i)))->~G__Tmcalguess();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (mcalguess*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((mcalguess*) (soff))->~G__Tmcalguess();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__mcalimagingDict_674_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   mcalguess* dest = (mcalguess*) G__getstructoffset();
   *dest = *(mcalguess*) libp->para[0].ref;
   const mcalguess& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* mcalguess */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncmcalimagingDict {
 public:
  G__Sizep2memfuncmcalimagingDict(): p(&G__Sizep2memfuncmcalimagingDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncmcalimagingDict::*p)();
};

size_t G__get_sizep2memfuncmcalimagingDict()
{
  G__Sizep2memfuncmcalimagingDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancemcalimagingDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__mcalimagingDictLN_mcalguess))) {
     mcalguess *G__Lderived;
     G__Lderived=(mcalguess*)0x1000;
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__mcalimagingDictLN_mcalguess),G__get_linked_tagnum(&G__mcalimagingDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__mcalimagingDictLN_mcalguess),G__get_linked_tagnum(&G__mcalimagingDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablemcalimagingDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mcalimagingDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mcalimagingDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mcalimagingDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mcalimagingDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__mcalimagingDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__mcalimagingDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__mcalimagingDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mcalimagingDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mcalimagingDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__mcalimagingDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__mcalimagingDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* mcalguess */
static void G__setup_memvarmcalguess(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__mcalimagingDictLN_mcalguess));
   { mcalguess *p; p=(mcalguess*)0x1000; if (p) { }
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"nevt[6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,2,"dim=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,2,"econv=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"mguess=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"kbin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"energybins[7]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"avgenergy[6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,2,"evtprob[6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,2,"ebinX[25]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,2,"ebinZ[25]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,2,"prob[6][16][16][24][24]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"currnbarsX=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"currnbarsZ=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,2,"curreX=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,2,"curreZ=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,2,"avgE=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mcalimagingDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarmcalimagingDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncmcalguess(void) {
   /* mcalguess */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__mcalimagingDictLN_mcalguess));
   G__memfunc_setup("mcalguess",964,G__mcalimagingDict_674_0_1, 105, G__get_linked_tagnum(&G__mcalimagingDictLN_mcalguess), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Fill",391,G__mcalimagingDict_674_0_2, 121, -1, -1, 0, 5, 1, 1, 0, 
"i - - 0 - nbin i - - 0 - nbarsX "
"i - - 0 - nbarsZ f - - 0 - eX "
"f - - 0 - eZ", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNEvents",995,G__mcalimagingDict_674_0_3, 73, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNEvents",995,G__mcalimagingDict_674_0_4, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBinProb",972,G__mcalimagingDict_674_0_5, 70, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBinProb",972,G__mcalimagingDict_674_0_6, 70, -1, -1, 0, 5, 1, 1, 0, 
"i - - 0 - nbarsX i - - 0 - nbarsZ "
"f - - 0 - eX f - - 0 - eZ "
"g - - 0 'FALSE' verbose", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBestBin",967,G__mcalimagingDict_674_0_7, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBestBin",967,G__mcalimagingDict_674_0_8, 105, -1, -1, 0, 5, 1, 1, 0, 
"i - - 0 - nbarsX i - - 0 - nbarsZ "
"f - - 0 - eX f - - 0 - eZ "
"g - - 0 'FALSE' verbose", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBestEnergy",1304,G__mcalimagingDict_674_0_9, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBestEnergy",1304,G__mcalimagingDict_674_0_10, 105, -1, -1, 0, 5, 1, 1, 0, 
"i - - 0 - nbarsX i - - 0 - nbarsZ "
"f - - 0 - eX f - - 0 - eZ "
"g - - 0 'FALSE' verbose", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBarCorr",971,G__mcalimagingDict_674_0_11, 85, G__get_linked_tagnum(&G__mcalimagingDictLN_TH2F), -1, 0, 2, 1, 1, 0, 
"i - - 0 - ibin g - - 0 'FALSE' verbose", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergyCorr",1312,G__mcalimagingDict_674_0_12, 85, G__get_linked_tagnum(&G__mcalimagingDictLN_TH2F), -1, 0, 2, 1, 1, 0, 
"i - - 0 - ibin g - - 0 'FALSE' verbose", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetKalmanProb",1287,G__mcalimagingDict_674_0_13, 102, -1, -1, 0, 2, 1, 1, 0, 
"f - - 0 - EK g - - 0 'FALSE' verbose", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetKalmanBin",1165,G__mcalimagingDict_674_0_14, 102, -1, -1, 0, 2, 1, 1, 0, 
"f - - 0 - EK g - - 0 'FALSE' verbose", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Normalize",945,G__mcalimagingDict_674_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - ibin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEnergyArray",1429,G__mcalimagingDict_674_0_16, 121, -1, -1, 0, 3, 1, 1, 0, 
"D - - 0 - earr F - - 0 - eXarr "
"F - - 0 - eZarr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintVerbose",1251,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintKalmanVerbose",1847,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 2, 0, "f - - 0 - EK", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Calculate",910,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 4, 1, 2, 0, 
"i - - 0 - nbarsX i - - 0 - nbarsZ "
"f - - 0 - eX f - - 0 - eZ", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculateKalman",1506,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 2, 0, "f - - 0 - EK", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__mcalimagingDict_674_0_21, 85, G__get_linked_tagnum(&G__mcalimagingDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&mcalguess::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__mcalimagingDict_674_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&mcalguess::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__mcalimagingDict_674_0_23, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&mcalguess::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__mcalimagingDict_674_0_24, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&mcalguess::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__mcalimagingDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__mcalimagingDict_674_0_28, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__mcalimagingDict_674_0_29, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&mcalguess::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__mcalimagingDict_674_0_30, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&mcalguess::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__mcalimagingDict_674_0_31, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&mcalguess::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__mcalimagingDict_674_0_32, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&mcalguess::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("mcalguess", 964, G__mcalimagingDict_674_0_33, (int) ('i'), G__get_linked_tagnum(&G__mcalimagingDictLN_mcalguess), -1, 0, 1, 1, 1, 0, "u 'mcalguess' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~mcalguess", 1090, G__mcalimagingDict_674_0_34, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__mcalimagingDict_674_0_35, (int) ('u'), G__get_linked_tagnum(&G__mcalimagingDictLN_mcalguess), -1, 1, 1, 1, 1, 0, "u 'mcalguess' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncmcalimagingDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalmcalimagingDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcmcalimagingDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__mcalimagingDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__mcalimagingDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__mcalimagingDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__mcalimagingDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__mcalimagingDictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__mcalimagingDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__mcalimagingDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mcalimagingDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__mcalimagingDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mcalimagingDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__mcalimagingDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__mcalimagingDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__mcalimagingDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__mcalimagingDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__mcalimagingDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__mcalimagingDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__mcalimagingDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__mcalimagingDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__mcalimagingDictLN_TH2F = { "TH2F" , 99 , -1 };
G__linked_taginfo G__mcalimagingDictLN_mcalguess = { "mcalguess" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablemcalimagingDict() {
  G__mcalimagingDictLN_TClass.tagnum = -1 ;
  G__mcalimagingDictLN_TBuffer.tagnum = -1 ;
  G__mcalimagingDictLN_TMemberInspector.tagnum = -1 ;
  G__mcalimagingDictLN_TObject.tagnum = -1 ;
  G__mcalimagingDictLN_TNamed.tagnum = -1 ;
  G__mcalimagingDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__mcalimagingDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mcalimagingDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__mcalimagingDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mcalimagingDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__mcalimagingDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__mcalimagingDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__mcalimagingDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__mcalimagingDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mcalimagingDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__mcalimagingDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__mcalimagingDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__mcalimagingDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__mcalimagingDictLN_TH2F.tagnum = -1 ;
  G__mcalimagingDictLN_mcalguess.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablemcalimagingDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_TNamed);
   G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_TH2F);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__mcalimagingDictLN_mcalguess),sizeof(mcalguess),-1,62720,(char*)NULL,G__setup_memvarmcalguess,G__setup_memfuncmcalguess);
}
extern "C" void G__cpp_setupmcalimagingDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupmcalimagingDict()");
  G__set_cpp_environmentmcalimagingDict();
  G__cpp_setup_tagtablemcalimagingDict();

  G__cpp_setup_inheritancemcalimagingDict();

  G__cpp_setup_typetablemcalimagingDict();

  G__cpp_setup_memvarmcalimagingDict();

  G__cpp_setup_memfuncmcalimagingDict();
  G__cpp_setup_globalmcalimagingDict();
  G__cpp_setup_funcmcalimagingDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncmcalimagingDict();
  return;
}
class G__cpp_setup_initmcalimagingDict {
  public:
    G__cpp_setup_initmcalimagingDict() { G__add_setup_func("mcalimagingDict",(G__incsetup)(&G__cpp_setupmcalimagingDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initmcalimagingDict() { G__remove_setup_func("mcalimagingDict"); }
};
G__cpp_setup_initmcalimagingDict G__cpp_setup_initializermcalimagingDict;

